//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HotelManagementApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomBookings
    {
        public int BookingId { get; set; }
        public string CustomerFirstName { get; set; }
        public string CustomerLastName { get; set; }
        public string CustomerPhoneNumber { get; set; }
        public bool CustomerAge { get; set; }
        public string CustomerEmail { get; set; }
        public string CustomerAddress { get; set; }
        public System.DateTime BookingFrom { get; set; }
        public System.DateTime BookingUntil { get; set; }
        public int AssignRoomId { get; set; }
        public int NumberOfMembers { get; set; }
        public decimal TotalAmount { get; set; }
    }
}
